branches:
  except:
    - /libpng[0-1][0-7]/

language: c

os:
  - freebsd
  - linux
  - osx

env:
  - AUTOMATION=cmake CI_NO_TEST=1
  - AUTOMATION=cmake CI_CMAKE_VARS="-DPNG_HARDWARE_OPTIMIZATIONS=ON" CI_SANITIZERS="address,undefined"
  - AUTOMATION=cmake CI_CMAKE_VARS="-DPNG_HARDWARE_OPTIMIZATIONS=OFF" CI_SANITIZERS="address,undefined"
  - AUTOMATION=configure CI_NO_TEST=1
  - AUTOMATION=configure CI_CONFIGURE_FLAGS="--enable-hardware-optimizations"
  - AUTOMATION=configure CI_CONFIGURE_FLAGS="--disable-hardware-optimizations"
  - AUTOMATION=makefiles CI_NO_TEST=1
  - AUTOMATION=makefiles CI_SANITIZERS="address,undefined"

matrix:
  include:
    - os: osx
      env: AUTOMATION=cmake CI_CMAKE_GENERATOR=Xcode

before_script:
  - 'if test "$TRAVIS_OS_NAME" = "linux"; then COMPILER="gcc"; else COMPILER="clang"; fi'
  - 'export CI_MAKEFILES="scripts/makefile.std scripts/makefile.$COMPILER"'
  - 'export CI_MAKE_FLAGS="-j2"'
  - 'export CI_CMAKE_BUILD_FLAGS="--parallel 2"'
  - 'export CI_CTEST_FLAGS="--parallel 2"'

script:
  - './ci/ci_verify_$AUTOMATION.sh'
